spring:
  devtools:
    restart:
      enabled: ${DEV_TOOL_ENABLED}
      additional-paths: src
  data:
      mongodb:
        host: ${MONGO_HOST}
        database: ${MONGO_DB_NAME}
        username: ${MONGO_USER}
        password: ${MONGO_PASSWORD}
line:
  bot:
    channelToken: ${LINE_CHANNEL_TOKEN}
    channelSecret: ${LINE_CHANNEL_SECRET}
  getAccessTokenUrl: ${LINE_GET_ACCESS_TOKEN_URL}
  clientId: ${LINE_CLIENT_ID}
  clientSecret: ${LINE_CLIENT_SECRET}
  grantType: ${LINE_GRANT_TYPE}
  redirectUri: ${LINE_REDIRECT_URI}
web:
  url: ${WEB_URL}
server:
  port: ${PORT}